[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  name = "github.com/ericlagergren/decimal"
  version = "3.3.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  branch = "master"
  name = "github.com/sigurn/crc16"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.4.0"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
